### ISSUE TITLE
tests doesn't run unless dependencies are added

### ISSUE THREAD

**Issue by tveimo** [mwanji/humpty-less#2]
Looks like I have to add these dependencies to get the tests to run;

```
    <dependency>
        <groupId>org.antlr</groupId>
        <artifactId>antlr-runtime</artifactId>
        <version>3.5.2</version>
    </dependency>
    <dependency>
        <groupId>commons-beanutils</groupId>
        <artifactId>commons-beanutils</artifactId>
        <version>1.9.2</version>
    </dependency>
```

**Comment by mwanji** [comment]
Those are dependencies of less4j and should be automatically brought in transitively.

What OS, Java version and Maven version are you running this on? What's the error output? mvn test works for me without these dependencies.

**Comment by tveimo** [comment]
Hmm, looks like I overlooked this error;

[WARNING] The POM for com.github.sommeri:less4j:jar:1.8.4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Comment by tveimo** [comment]
You can close this issue, the less4j pom file in my .m2 repo was invalid, it contained json instead of xml for some reason.
